name: louisbutcheryapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  get: ^4.7.2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/FINAL logo with arabic LOW QUALITY.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/Logo Low Quality.png
    - images/575.webp
